version: '2.2'

services:
  dp_mongodb:
    image: mongo:latest
    volumes:
      - ~/apps/mongo:/data/db
    command: --bind_ip 0.0.0.0
  dp_lifecycle:
    build: ./dp_lifecycle
    ports:
      - "1200:80"
  dp_server:
    build: ./app
    ports: 
      - "5000:5000"
    links:
      - dp_mongodb
    environment:
      - IS_DOCKER=true
