version: '3.9'

services:
  dp_mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ~/apps/mongo:/data/db
    command: --bind_ip 0.0.0.0
  dp_lifecycle:
    build: ./dp_lifecycle
    ports:
      - "1200:80"
  dp_server:
    build: ./app
    ports: 
      - "5000:5000"
    links:
      - dp_mongodb
    environment:
      - M_USERNAME=$M_USERNAME
      - M_PASSWORD=$M_PASSWORD
      - IS_DOCKER=true
